name    'theforeman-foreman-ipa'
version '0.0.1'
source 'git://github.com/theforeman/puppet-foreman-ipa'
author 'theforeman'
license 'GPLv3+'
summary 'Foreman IPA integration'
description 'Module for configuring Foreman and IPA client to enable SSO and external user management'
project_page 'http://github.com/theforeman/foreman-installer'

dependency 'stbenjam/ipaclient', '>= 2.2.1'
